"""Per-room image registry for group rooms.

Group sessions are stateless and room history (fetch_recent_messages) is text-only,
so "edit the last image" was unresolvable: neither uploaded nor bot-generated image
paths survive the turn. This registry records both, and the group prompt gets a small
"[Images in this room]" block so the model can reference them directly by path.
Persisted in <config_dir>/room_images.json (restart-safe).
"""
from __future__ import annotations

import json
import threading
import time
from pathlib import Path
from typing import Any

_LOCK = threading.Lock()
_MAX_PER_ROOM = 10   # stored per room
_BLOCK_LIMIT = 5     # rendered into the prompt


def _store_path(config: dict[str, Any]) -> Path:
    config_dir = config.get("_config_dir") or ""
    if not config_dir:
        from miniassistant.config import get_config_dir
        config_dir = get_config_dir()
    return Path(config_dir) / "room_images.json"


def _room_key(ctx: dict[str, Any]) -> str | None:
    platform = ctx.get("platform") or ""
    rid = ctx.get("room_id") or ctx.get("channel_id") or ""
    if not platform or not rid:
        return None
    return f"{platform}:{rid}"


def record_image(config: dict[str, Any], host_path: str, who: str, kind: str) -> None:
    """Record an image for the current group room. kind: 'upload' | 'generated'.
    No-op outside group rooms (DM/web images live in the normal session context)."""
    ctx = config.get("_chat_context") or {}
    if not ctx.get("group_mode"):
        return
    key = _room_key(ctx)
    if not key or not host_path:
        return
    sp = _store_path(config)
    entry = {"ts": int(time.time()), "path": str(host_path), "who": who or "?", "kind": kind}
    with _LOCK:
        try:
            data = json.loads(sp.read_text(encoding="utf-8")) if sp.exists() else {}
        except Exception:
            data = {}
        items = [it for it in (data.get(key) or []) if it.get("path") != str(host_path)]
        items.append(entry)
        data[key] = items[-_MAX_PER_ROOM:]
        try:
            tmp = sp.with_suffix(".tmp")
            tmp.write_text(json.dumps(data, ensure_ascii=False), encoding="utf-8")
            tmp.replace(sp)
        except OSError:
            pass


def format_block(config: dict[str, Any], ctx: dict[str, Any]) -> str:
    """Prompt block listing this room's images, newest first. '' if none.
    Paths are shown in sandbox view (/workspace/…) when inside the room workspace —
    the same form invoke_model/send_image accept in group mode."""
    if not ctx.get("group_mode"):
        return ""
    key = _room_key(ctx)
    if not key:
        return ""
    sp = _store_path(config)
    try:
        data = json.loads(sp.read_text(encoding="utf-8")) if sp.exists() else {}
    except Exception:
        return ""
    items = data.get(key) or []
    if not items:
        return ""
    ws: Path | None = None
    try:
        from miniassistant.group_rooms import group_workspace_path
        ws = Path(group_workspace_path(config, ctx.get("workspace_subdir") or "default")).resolve()
    except Exception:
        pass
    lines: list[str] = []
    for it in reversed(items):
        p = Path(str(it.get("path") or ""))
        if not p.exists():
            continue
        disp = str(p)
        if ws is not None:
            try:
                disp = "/workspace/" + str(p.resolve().relative_to(ws))
            except (ValueError, OSError):
                pass
        hm = time.strftime("%H:%M %d.%m.", time.localtime(it.get("ts") or 0))
        src = "generated by you" if it.get("kind") == "generated" else f"uploaded by {it.get('who') or '?'}"
        lines.append(f"{len(lines) + 1}. `{disp}` — {src}, {hm}")
        if len(lines) >= _BLOCK_LIMIT:
            break
    if not lines:
        return ""
    return (
        "[Images in this room — newest first. \"the last image\" / \"das letzte Bild\" = #1.\n"
        " To EDIT one: pass its path as `image_path` to invoke_model. Do NOT guess other paths.]\n"
        + "\n".join(lines)
        + "\n\n"
    )
